---
title: "Plot"
author: "Abdullah Sourav"
date: "November 21, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{python}

import arcpy, os, numpy,fnmatch, pandas as pd, numpy as np
from arcpy.sa import *
from datetime import datetime
import matplotlib.pyplot as plt


dataframe = pd.DataFrame(columns=['Value', 'Date', 'Satellite'])

for root, dirs, files in os.walk(r"E:\Current Work Folder\Field Trip data\accola"):
    for file in files:
        if file.endswith("NDVI.tif") and (fnmatch.fnmatch(file, "*PSC*") or fnmatch.fnmatch(file, "*Intel*")):
            print (file, "is being processed")
            
            if fnmatch.fnmatch(file, "*Intel*"):
                inRaster = os.path.join(root, file)
                i = Aggregate(inRaster, 9, "MEAN", "TRUNCATE", "NODATA")
            else:
                i = os.path.join(root, file)
            array = arcpy.RasterToNumPyArray(i,nodata_to_value=9999)
            xarray =array.flatten()
            index = np.argwhere(xarray==9999)
            x = np.delete(xarray, index)
            p5 = numpy.percentile(xarray,5)
            p95 = numpy.percentile(xarray,95)
            index2 = np.argwhere(x<p5)
            y1=  np.delete(x, index2)
            index3 = np.argwhere(x>p5)
            y=  np.delete(y1, index3)
            
            if fnmatch.fnmatch(file, "*Intel*"):
                Satellite = "PSC"           
            else:
                Satellite = "Intel"
            
            datename = file[-19:-11]
            date = datetime.strptime(datename[0:4]+"."+datename[4:6]+"."+datename[6:], '%Y.%m.%d')
            df2 =  pd.DataFrame({'Value': y, 'Date':[date]*y.size, 'Satellite':[Satellite]*y.size})
            dataframe = pd.concat([dataframe,df2], ignore_index=True)
    
dataframe.to_csv("C:/Users/Sourav/Desktop/d3.csv")
```



```{r}
require(ggplot2)
require(visreg)
require(MASS)
require(reshape2)
library(scales)


x = read.csv("C:/Users/Sourav/Desktop/d3.csv",header = T)

str(x) 



x$asDate = as.Date(x[,2], "%Y-%m-%d")

p<-ggplot(data =x, aes(x = asDate, y = Value, group=interaction(asDate, Satellite)))
p +  geom_boxplot(aes(fill = factor(x$Satellite)))+ scale_x_date(date_breaks = "1 week", date_labels = "%b %d")+labs(title = "Time Series Box Plot", x = "Date", y= "NDVI value")+scale_fill_discrete(name="Satellite")

ggsave("plot.png", width = 15, height = 10, units = "in", dpi= 600)

```










